import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./common/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./apps/stitch-web/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./page.tsx",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#171a1d",
        "outline": "#747579",
        "tertiary-container": "#70d6ff",
        "primary-fixed-dim": "#f16092",
        "on-primary-container": "#4c0022",
        "primary": "#ff89ad",
        "on-primary": "#62002e",
        "surface-bright": "#292c31",
        "on-tertiary-container": "#00485d",
        "on-secondary-container": "#e0ffec",
        "error": "#ff6e84",
        "error-dim": "#d73357",
        "inverse-surface": "#f9f9fd",
        "secondary-fixed": "#59faba",
        "background": "#0c0e11",
        "secondary-dim": "#47ecad",
        "on-secondary": "#005c3f",
        "on-surface": "#e8e8ec",
        "surface-dim": "#0c0e11",
        "secondary-container": "#006c4b",
        "on-tertiary-fixed-variant": "#005269",
        "error-container": "#a70138",
        "surface-variant": "#23262a",
        "inverse-primary": "#ad2b5e",
        "on-tertiary": "#005269",
        "primary-fixed": "#ff709f",
        "on-secondary-fixed": "#004730",
        "secondary-fixed-dim": "#47ecad",
        "surface-container-low": "#111317",
        "secondary": "#59faba",
        "surface-tint": "#ff89ad",
        "on-secondary-fixed-variant": "#006747",
        "on-tertiary-fixed": "#003342",
        "surface": "#0c0e11",
        "tertiary": "#9de1ff",
        "primary-container": "#ff709f",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#23262a",
        "tertiary-fixed-dim": "#60c8f0",
        "outline-variant": "#46484b",
        "on-background": "#e8e8ec",
        "on-primary-fixed-variant": "#5d002b",
        "on-primary-fixed": "#000000",
        "surface-container-high": "#1d2024",
        "on-error": "#490013",
        "primary-dim": "#ff6b9d",
        "on-surface-variant": "#aaabaf",
        "on-error-container": "#ffb2b9",
        "inverse-on-surface": "#535559",
        "tertiary-dim": "#60c8f0",
        "tertiary-fixed": "#70d6ff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
      },
    },
  },
  plugins: [],
};
export default config;